name: Remove Prohibited Control Code Points

on: [push, pull_request]

jobs:
  remove-control-codes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run control code removal script
      run: python remove_control_code.py
